<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.15"/>
    <xacro:property name="base_width" value="0.055"/>
    <xacro:property name="base_height" value="0.095"/>
    <xacro:property name="wheel_radius" value="${base_height / 2.0}"/>
    <xacro:property name="wheel_length" value="${wheel_radius / 2.0}"/>

    <xacro:macro name="wheel_link" params="side">
        <link name="${side}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia r="${2 * wheel_radius}" l="${2 * wheel_length}" m="1.0" xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <link name="base_footprint" />

    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia l="${2 * base_length}" w="${2 * base_width}" h="${2 * base_height}" m="${5.0}" xyz = "0 0 ${2 * base_height / 2.0}" rpy = "0 0 0" />
    </link>


    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </joint>
</robot>