<?xml version="1.0"?>
<package format="3">
  <name>rasptank_enrico_paper</name>
  <version>0.0.0</version>
  <description>Enrico paper example node adapted for rasptank: subscribes to /odom and publishes /cmd_vel</description>
  <maintainer email="sami@example.com">sami</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>std_msgs</depend>
  <depend>turtlesim</depend>
  <exec_depend>setuptools</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>

</package>
